### ISSUE TITLE
Newline missing

### ISSUE THREAD

**Issue by SchnitzlerGerd** [mauricerenck/mastodon-to-bluesky#12]
Newlines in toots are filtered out.
Tooting
"Lorem
ipsum
dolor sit amet"

becomes
"Loremipsumdolor sit amet" 
in BlueSky..

**Comment by alien-sunset** [comment]
just popping in to confirm that this is happening to me too, it's rather vexing.

**Comment by alien-sunset** [comment]
oop, looks like it doesn't like quotes either, an links go through all non link-y
![image](https://github.com/user-attachments/assets/a03aa2b1-258d-423b-86db-40a48aeacf11)

**Comment by alien-sunset** [comment]
something like this may be better than the current non discriminatory html stripping code:
https://www.npmjs.com/package/html-to-text

it adds a bit of extra complexity needing the outside library, but it should ensure that newlines and special characters don't get messed up.

**Comment by WhiteFangs** [comment]
I fixed this issue on [my fork](https://github.com/WhiteFangs/mastodon-to-bluesky) that is based on [another fork](https://code.alexhyett.com/alexhyett/mastodon-to-bluesky) of this repo.
The repo I forked from has replaced the `removeHtmlTags` method with a `sanitizeHtml` one and I fixed it to handle line breaks, the corresponding commit is here: https://github.com/WhiteFangs/mastodon-to-bluesky/commit/a2dc0facb28bc8998196c7b15a6223776f02ca30

**Comment by WhiteFangs** [comment]
I actually noticed a bug on my side after commenting here, the following line:
```
      const addSpace = decodeQuotes.replace(/(https?:\/\/)/g, ' $1');
```
removed the line breaks that were added in the previous lines, so I just had to remove it to fix that, not sure if the same problem could happen on your side here.
Adding a space before links is not actually relevant if the toot already has a space before the link (which it naturally should).
